#!/bin/bash
# Sync SMTP config from e_sysparam DB table → /etc/msmtprc
# Called by monitor.sh before sending alert emails
set -e

ENV_FILE="/home/kunshiweb/vos-billing/.env"
MSMTPRC="/etc/msmtprc"

# Load DB credentials from .env
if [ -f "$ENV_FILE" ]; then
  export $(grep -v '^#' "$ENV_FILE" | xargs)
fi

DB_HOST="${VOS_DB_HOST:-127.0.0.1}"
DB_PORT="${VOS_DB_PORT:-3306}"
DB_USER="${VOS_DB_USER:-root}"
DB_PASS="${VOS_DB_PASSWORD:-}"
DB_NAME="${VOS_DB_NAME:-vos3000}"

# Query SMTP params from e_sysparam (same as lib/email.ts)
MYSQL_OPTS="-h $DB_HOST -P $DB_PORT -u $DB_USER"
[ -n "$DB_PASS" ] && MYSQL_OPTS="$MYSQL_OPTS -p$DB_PASS"

read_smtp_param() {
  local name="$1"
  mysql $MYSQL_OPTS "$DB_NAME" -sN -e \
    "SELECT param_value FROM e_sysparam WHERE param_name='$name' LIMIT 1" 2>/dev/null || echo ""
}

SMTP_HOST=$(read_smtp_param "smtp_host")
SMTP_PORT=$(read_smtp_param "smtp_port")
SMTP_USER=$(read_smtp_param "smtp_user")
SMTP_PASS=$(read_smtp_param "smtp_pass")
SMTP_FROM=$(read_smtp_param "smtp_from")
SMTP_SECURE=$(read_smtp_param "smtp_secure")

if [ -z "$SMTP_HOST" ]; then
  echo "[sync-smtp] No SMTP host configured in e_sysparam — skipping"
  exit 0
fi

SMTP_PORT="${SMTP_PORT:-587}"

# Determine TLS settings based on port
# Port 465 = implicit SSL (TLS wrapper), Port 587 = STARTTLS
if [ "$SMTP_PORT" = "465" ] || [ "$SMTP_SECURE" = "ssl" ]; then
  TLS="on"
  TLS_STARTTLS="off"
else
  TLS="on"
  TLS_STARTTLS="on"
fi

# Match nodemailer behavior (lib/email.ts uses rejectUnauthorized: false)
# Always skip cert verification — SMTP servers often have self-signed/expired certs
TLS_TRUST="# tls_trust_file skipped (tls_certcheck off — matching nodemailer rejectUnauthorized)"
TLS_CERTCHECK="tls_certcheck off"

# Generate msmtprc
sudo tee "$MSMTPRC" > /dev/null << MSMTPEOF
# Auto-generated by vos-billing/scripts/sync-smtp-config.sh
# Do not edit manually — SMTP settings come from e_sysparam DB

defaults
auth           login
tls            $TLS
tls_starttls   $TLS_STARTTLS
$TLS_TRUST
$TLS_CERTCHECK
logfile        /var/log/msmtp.log

account        vos
host           $SMTP_HOST
port           $SMTP_PORT
user           $SMTP_USER
password       $SMTP_PASS
from           ${SMTP_FROM:-$SMTP_USER}

account default : vos
MSMTPEOF

# Secure the file (contains password)
sudo chmod 600 "$MSMTPRC" 2>/dev/null || true

echo "[sync-smtp] SMTP config synced: $SMTP_HOST:$SMTP_PORT (user: $SMTP_USER)"
