import { NextRequest, NextResponse } from "next/server";
import { executeVos } from "@/lib/vos-db";
import { verifySession } from "@/lib/auth";

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { id } = await params;
    const body = await request.json();

    const gwId = parseInt(id);

    await executeVos(
      `UPDATE e_gatewaymapping SET
        name = ?, password = ?, customerpassword = ?, locktype = ?, calllevel = ?,
        capacity = ?, priority = ?, registertype = ?, remoteips = ?, rtpforwardtype = ?,
        gatewaygroups = ?, routinggatewaygroups = ?, memo = ?, customer_id = ?, mbx_id = ?
       WHERE id = ?`,
      [
        body.name || "",
        body.password || "",
        body.customerPassword || "",
        body.lockType ?? 0,
        body.callLevel ?? 0,
        body.capacity ?? 30,
        body.priority ?? 1,
        body.registerType ?? 0,
        body.remoteIps || "",
        body.rtpForwardType ?? 0,
        body.gatewayGroups || "",
        body.routingGatewayGroups || "",
        body.memo || "",
        body.customerId ?? 0,
        body.mbxId ?? 0,
        gwId,
      ]
    );

    // Update e_gatewaymappingsetting
    try {
      await executeVos(
        `UPDATE e_gatewaymappingsetting SET
          calloutcallerprefixesallow = ?, calloutcallerprefixes = ?,
          calloutcalleeprefixesallow = ?, calloutcalleeprefixes = ?,
          rewriterulesoutcallee = ?, rewriterulesoutcaller = ?,
          callerblacklistpolicy = ?, calleeblacklistpolicy = ?,
          calloutroutinggateways = ?,
          sipcodecs = ?, h323codecs = ?,
          dtmfreceivemethod = ?, dtmfsendmethodsip = ?,
          mediacheckdirection = ?, timeoutcallproceeding = ?,
          maxcalldurationlower = ?, maxcalldurationupper = ?,
          scheduledcalloutprefixes = ?, scheduledrewriterulesout = ?, scheduledcapacity = ?,
          callercitye164check = ?,
          calleecitye164check = ?,
          rewriterulesinmobilearea = ?,
          dtmfsendmethodh323 = ?,
          dtmfreceivepayloadtype = ?,
          dtmfsendpayloadtypeh323 = ?,
          dtmfsendpayloadtypesip = ?,
          q931progressindicator = ?,
          callfailedsipcode = ?,
          callfailedq931causevalue = ?,
          sipresponseaddressmethod = ?,
          siprequestaddressmethod = ?,
          sipremoteringsignal = ?,
          sipcalleee164domain = ?,
          sipcallere164domain = ?,
          h323calleee164domain = ?,
          h323callere164domain = ?,
          allowphonebilling = ?,
          allowbindede164billing = ?,
          enablephonesetting = ?,
          sipauthenticationmethod = ?,
          sipauthenticationuser = ?,
          calltransferbillingmode = ?,
          bitsofh323config = ?,
          bitsofsipconfig = ?,
          bitsofconfig = ?,
          callerallowlength = ?,
          calleeallowlength = ?,
          callerlimite164groups = ?,
          calleelimite164groups = ?,
          minprofitpercent = ?,
          firstroutepolicy = ?,
          secondroutepolicy = ?,
          h323g729sendmode = ?,
          sipg729sendmode = ?,
          sipg729annexb = ?,
          sipg723annexa = ?,
          calleee164restrict = ?,
          timeoutcallredirect = ?,
          maxcallrate = ?,
          maxcallrateunit = ?,
          timeoutredirecte164 = ?,
          calculatequality = ?,
          denysamecitycodes = ?,
          checkmobilearea = ?,
          externalrewritetype = ?,
          externalrewritetrigger = ?,
          sipremotepartyidscreen = ?,
          sipe164displayfrom = ?,
          sipextraheader = ?,
          tryprotectroutedelay = ?,
          forwardsignalrewritee164group = ?,
          maxsecondrates = ?,
          lrneatprefixlength = ?,
          lrnfailureaction = ?,
          lrninterstatebillingprefix = ?,
          lrnundeterminedbillingprefix = ?,
          traceendtime = ?,
          aassampling = ?,
          aaswordcategory = ?,
          language = ?,
          rewriteprefixaddoutcallee = ?,
          externalNumberVerifyBits = ?,
          externalNumberVerfiyRewriteCaller = ?,
          externalNumberVerfiyRewriteCallee = ?
         WHERE gatewaymapping_id = ?`,
        [
          body.calloutCallerPrefixesAllow ?? 1, body.calloutCallerPrefixes || "",
          body.calloutCalleePrefixesAllow ?? 1, body.calloutCalleePrefixes || "",
          body.rewriteRulesOutCallee || "", body.rewriteRulesOutCaller || "",
          body.callerBlacklistPolicy ?? 0, body.calleeBlacklistPolicy ?? 0,
          body.calloutRoutingGateways || "",
          body.sipCodecs || "", body.h323Codecs || "",
          body.dtmfReceiveMethod ?? 0, body.dtmfSendMethodSip ?? 0,
          body.mediaCheckDirection ?? 0, body.timeoutCallProceeding ?? 30,
          body.maxCallDurationLower ?? 0, body.maxCallDurationUpper ?? 0,
          body.scheduledCalloutPrefixes || "", body.scheduledRewriteRulesOut || "",
                    body.scheduledCapacity || "",
          body.callerCityE164Check ?? 0,
          body.calleeCityE164Check ?? 0,
          body.rewriteRulesInMobileArea || "",
          body.dtmfSendMethodH323 ?? 0,
          body.dtmfReceivePayloadType ?? 0,
          body.dtmfSendPayloadTypeH323 ?? 0,
          body.dtmfSendPayloadTypeSip ?? 0,
          body.q931ProgressIndicator ?? 0,
          body.callFailedSipCode || "",
          body.callFailedQ931CauseValue || "",
          body.sipResponseAddressMethod ?? 0,
          body.sipRequestAddressMethod ?? 0,
          body.sipRemoteRingSignal ?? 0,
          body.sipCalleeE164Domain ?? 0,
          body.sipCallerE164Domain ?? 0,
          body.h323CalleeE164Domain ?? 0,
          body.h323CallerE164Domain ?? 0,
          body.allowPhoneBilling ?? 0,
          body.allowBindedE164Billing ?? 0,
          body.enablePhoneSetting ?? 0,
          body.sipAuthenticationMethod ?? 0,
          body.sipAuthenticationUser || "",
          body.callTransferBillingMode ?? 0,
          body.bitsOfH323Config ?? 0,
          body.bitsOfSipConfig ?? 0,
          body.bitsOfConfig ?? 0,
          body.callerAllowLength ?? 0,
          body.calleeAllowLength ?? 0,
          body.callerLimitE164Groups || "",
          body.calleeLimitE164Groups || "",
          body.minProfitPercent ?? 0,
          body.firstRoutePolicy ?? 0,
          body.secondRoutePolicy ?? 0,
          body.h323G729SendMode ?? 0,
          body.sipG729SendMode ?? 0,
          body.sipG729AnnexB ?? 0,
          body.sipG723AnnexA ?? 0,
          body.calleeE164Restrict ?? 0,
          body.timeoutCallRedirect ?? 0,
          body.maxCallRate ?? 0,
          body.maxCallRateUnit ?? 0,
          body.timeoutRedirectE164 || "",
          body.calculateQuality ?? 0,
          body.denySameCityCodes || "",
          body.checkMobileArea || "",
          body.externalRewriteType ?? 0,
          body.externalRewriteTrigger || "",
          body.sipRemotePartyIdScreen ?? 0,
          body.sipE164DisplayFrom ?? 0,
          body.sipExtraHeader || "",
          body.tryProtectRouteDelay ?? 0,
          body.forwardSignalRewriteE164Group || "",
          body.maxSecondRates ?? 0.0,
          body.lrnEatPrefixLength ?? 0,
          body.lrnFailureAction ?? 0,
          body.lrnInterstateBillingPrefix || "",
          body.lrnUndeterminedBillingPrefix || "",
          body.traceEndTime ?? 0,
          body.aasSampling ?? 0.0,
          body.aasWordCategory || "",
          body.language || "",
          body.rewritePrefixAddOutCallee || "",
          body.externalNumberVerifyBits ?? 0,
          body.externalNumberVerifyRewriteCaller || "",
          body.externalNumberVerifyRewriteCallee || "",
          gwId,
        ]
      );
    } catch {
      await executeVos(
        `INSERT INTO e_gatewaymappingsetting (gatewaymapping_id, calloutcallerprefixesallow, calloutcallerprefixes,
          calloutcalleeprefixesallow, calloutcalleeprefixes,
          rewriterulesoutcallee, rewriterulesoutcaller,
          callerblacklistpolicy, calleeblacklistpolicy,
          calloutroutinggateways,
          sipcodecs, h323codecs, dtmfreceivemethod, dtmfsendmethodsip,
          mediacheckdirection, timeoutcallproceeding,
          maxcalldurationlower, maxcalldurationupper,
          scheduledcalloutprefixes, scheduledrewriterulesout, scheduledcapacity,
          callercitye164check,
          calleecitye164check,
          rewriterulesinmobilearea,
          dtmfsendmethodh323,
          dtmfreceivepayloadtype,
          dtmfsendpayloadtypeh323,
          dtmfsendpayloadtypesip,
          q931progressindicator,
          callfailedsipcode,
          callfailedq931causevalue,
          sipresponseaddressmethod,
          siprequestaddressmethod,
          sipremoteringsignal,
          sipcalleee164domain,
          sipcallere164domain,
          h323calleee164domain,
          h323callere164domain,
          allowphonebilling,
          allowbindede164billing,
          enablephonesetting,
          sipauthenticationmethod,
          sipauthenticationuser,
          calltransferbillingmode,
          bitsofh323config,
          bitsofsipconfig,
          bitsofconfig,
          callerallowlength,
          calleeallowlength,
          callerlimite164groups,
          calleelimite164groups,
          minprofitpercent,
          firstroutepolicy,
          secondroutepolicy,
          h323g729sendmode,
          sipg729sendmode,
          sipg729annexb,
          sipg723annexa,
          calleee164restrict,
          timeoutcallredirect,
          maxcallrate,
          maxcallrateunit,
          timeoutredirecte164,
          calculatequality,
          denysamecitycodes,
          checkmobilearea,
          externalrewritetype,
          externalrewritetrigger,
          sipremotepartyidscreen,
          sipe164displayfrom,
          sipextraheader,
          tryprotectroutedelay,
          forwardsignalrewritee164group,
          maxsecondrates,
          lrneatprefixlength,
          lrnfailureaction,
          lrninterstatebillingprefix,
          lrnundeterminedbillingprefix,
          traceendtime,
          aassampling,
          aaswordcategory,
          language,
          rewriteprefixaddoutcallee,
          externalNumberVerifyBits,
          externalNumberVerfiyRewriteCaller,
          externalNumberVerfiyRewriteCallee)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [gwId,
          body.calloutCallerPrefixesAllow ?? 1, body.calloutCallerPrefixes || "",
          body.calloutCalleePrefixesAllow ?? 1, body.calloutCalleePrefixes || "",
          body.rewriteRulesOutCallee || "", body.rewriteRulesOutCaller || "",
          body.callerBlacklistPolicy ?? 0, body.calleeBlacklistPolicy ?? 0,
          body.calloutRoutingGateways || "",
          body.sipCodecs || "", body.h323Codecs || "",
          body.dtmfReceiveMethod ?? 0, body.dtmfSendMethodSip ?? 0,
          body.mediaCheckDirection ?? 0, body.timeoutCallProceeding ?? 30,
          body.maxCallDurationLower ?? 0, body.maxCallDurationUpper ?? 0,
          body.scheduledCalloutPrefixes || "", body.scheduledRewriteRulesOut || "",
                    body.scheduledCapacity || "",
          body.callerCityE164Check ?? 0,
          body.calleeCityE164Check ?? 0,
          body.rewriteRulesInMobileArea || "",
          body.dtmfSendMethodH323 ?? 0,
          body.dtmfReceivePayloadType ?? 0,
          body.dtmfSendPayloadTypeH323 ?? 0,
          body.dtmfSendPayloadTypeSip ?? 0,
          body.q931ProgressIndicator ?? 0,
          body.callFailedSipCode || "",
          body.callFailedQ931CauseValue || "",
          body.sipResponseAddressMethod ?? 0,
          body.sipRequestAddressMethod ?? 0,
          body.sipRemoteRingSignal ?? 0,
          body.sipCalleeE164Domain ?? 0,
          body.sipCallerE164Domain ?? 0,
          body.h323CalleeE164Domain ?? 0,
          body.h323CallerE164Domain ?? 0,
          body.allowPhoneBilling ?? 0,
          body.allowBindedE164Billing ?? 0,
          body.enablePhoneSetting ?? 0,
          body.sipAuthenticationMethod ?? 0,
          body.sipAuthenticationUser || "",
          body.callTransferBillingMode ?? 0,
          body.bitsOfH323Config ?? 0,
          body.bitsOfSipConfig ?? 0,
          body.bitsOfConfig ?? 0,
          body.callerAllowLength ?? 0,
          body.calleeAllowLength ?? 0,
          body.callerLimitE164Groups || "",
          body.calleeLimitE164Groups || "",
          body.minProfitPercent ?? 0,
          body.firstRoutePolicy ?? 0,
          body.secondRoutePolicy ?? 0,
          body.h323G729SendMode ?? 0,
          body.sipG729SendMode ?? 0,
          body.sipG729AnnexB ?? 0,
          body.sipG723AnnexA ?? 0,
          body.calleeE164Restrict ?? 0,
          body.timeoutCallRedirect ?? 0,
          body.maxCallRate ?? 0,
          body.maxCallRateUnit ?? 0,
          body.timeoutRedirectE164 || "",
          body.calculateQuality ?? 0,
          body.denySameCityCodes || "",
          body.checkMobileArea || "",
          body.externalRewriteType ?? 0,
          body.externalRewriteTrigger || "",
          body.sipRemotePartyIdScreen ?? 0,
          body.sipE164DisplayFrom ?? 0,
          body.sipExtraHeader || "",
          body.tryProtectRouteDelay ?? 0,
          body.forwardSignalRewriteE164Group || "",
          body.maxSecondRates ?? 0.0,
          body.lrnEatPrefixLength ?? 0,
          body.lrnFailureAction ?? 0,
          body.lrnInterstateBillingPrefix || "",
          body.lrnUndeterminedBillingPrefix || "",
          body.traceEndTime ?? 0,
          body.aasSampling ?? 0.0,
          body.aasWordCategory || "",
          body.language || "",
          body.rewritePrefixAddOutCallee || "",
          body.externalNumberVerifyBits ?? 0,
          body.externalNumberVerifyRewriteCaller || "",
          body.externalNumberVerifyRewriteCallee || "",
        ]
      );
    }

    return NextResponse.json({ success: true });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed to update mapping gateway" }, { status: 500 });
  }
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { id } = await params;
    await executeVos("DELETE FROM e_gatewaymapping WHERE id = ?", [parseInt(id)]);
    return NextResponse.json({ success: true });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed to delete mapping gateway" }, { status: 500 });
  }
}
