import { NextRequest, NextResponse } from "next/server";
import { queryVos, executeVos } from "@/lib/vos-db";
import { verifySession } from "@/lib/auth";

export async function PUT(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { id } = await params;
    const body = await request.json();

    const gwId = parseInt(id);

    // Update e_gatewayrouting (main table)
    await executeVos(
      `UPDATE e_gatewayrouting SET
        name = ?, prefix = ?, prefixstyle = ?, password = ?, customerpassword = ?,
        locktype = ?, calllevel = ?, capacity = ?, priority = ?, protocol = ?,
        remoteips = ?, rtpforwardtype = ?, signalport = ?, signalportlocal = ?, gatewaygroups = ?, memo = ?, clearingcustomer_id = ?
       WHERE id = ?`,
      [
        body.name || "",
        body.prefix || "",
        body.prefixStyle ?? 0,
        body.password || "",
        body.customerPassword || "",
        body.lockType ?? 0,
        body.callLevel ?? 0,
        body.capacity ?? 30,
        body.priority ?? 1,
        body.protocol ?? 0,
        body.remoteIps || "",
        body.rtpForwardType ?? 0,
        body.signalPort ?? 5060,
        body.signalPortLocal ?? 5060,
        body.gatewayGroups || "",
        body.memo || "",
        body.clearingCustomerId ?? 0,
        gwId,
      ]
    );

    // Update e_gatewayroutingsetting (routing rules, codecs, period settings)
    try {
      await executeVos(
        `UPDATE e_gatewayroutingsetting SET
          callincallerprefixesallow = ?, callincallerprefixes = ?,
          callincalleeprefixesallow = ?, callincalleeprefixes = ?,
          callinforwardprefixes = ?,
          callerblacklistpolicy = ?, calleeblacklistpolicy = ?,
          rewriterulesincallee = ?, rewriterulesincaller = ?,
          denycallercallee = ?,
          scheduledcapacity = ?, scheduledpriority = ?,
          scheduledcallinprefixes = ?, scheduledrewriterulesin = ?,
          sipcodecs = ?, h323codecs = ?,
          timeoutinvite = ?, timeoutringing = ?,
          callercitye164check = ?,
          calleecitye164check = ?,
          stopswitchafterolc = ?,
          clearingaccountusecalloute164 = ?,
          q931presentationindicator = ?,
          q931screeningindicator = ?,
          dtmfreceivemethod = ?,
          dtmfsendmethodh323 = ?,
          dtmfsendmethodsip = ?,
          dtmfreceivepayloadtype = ?,
          dtmfsendpayloadtypeh323 = ?,
          dtmfsendpayloadtypesip = ?,
          q931numberingplan = ?,
          q931numbertype = ?,
          sipresponseaddressmethod = ?,
          siprequestaddressmethod = ?,
          bitsofh323config = ?,
          bitsofsipconfig = ?,
          callerallowlength = ?,
          calleeallowlength = ?,
          leastcostrouting = ?,
          h323g729sendmode = ?,
          sipg729sendmode = ?,
          sipg729annexb = ?,
          sipg723annexa = ?,
          mediacheckdirection = ?,
          enablecalltransfer = ?,
          maxcalldurationlower = ?,
          maxcalldurationupper = ?,
          calleee164restrict = ?,
          enablephonedisplay = ?,
          switchuntilconnect = ?,
          maxcallrate = ?,
          maxcallrateunit = ?,
          sipremotepartyidscreen = ?,
          sipe164displaytype = ?,
          sipprivacytype = ?,
          sipppreferredidentitytype = ?,
          sippassertedidentitytype = ?,
          rewriterulesincallerusee164line = ?,
          bitsofconfig = ?,
          traceendtime = ?,
          externalNumberVerifyBits = ?,
          aassampling = ?,
          denysamecitycodes = ?,
          checkmobilearea = ?,
          rewriterulesinmobilearea = ?,
          rewriterulespidentity = ?,
          axbbrewriterules = ?,
          externalNumberVerfiyRewriteCaller = ?,
          externalNumberVerfiyRewriteCallee = ?,
          rewriterulesincallerusee164group = ?,
          callerlimite164groups = ?,
          calleelimite164groups = ?,
          sipinvitecode = ?,
          sipauthenticationuser = ?,
          sipextraheader = ?,
          forwardsignalrewritee164group = ?,
          aaswordcategory = ?,
          axbagroup = ?,
          axbinterface = ?,
          axbaccount = ?,
          timeoutsetup = ?,
          timeoutcallproceeding = ?,
          timeoutcallproceedingolc = ?,
          timeoutalerting = ?,
          timeouttrying = ?,
          timeoutsessionprogresssdp = ?,
          timeoutsessionprogress = ?,
          localip = ?, stopswitchafteruserbusy = ?, stopswitchaftersdp = ?, stopswitchafterrtpstart = ?,
          stopswitchsipcodes = ?,
          calculatequality = ?, minprofitpercent = ?, maxsecondrates = ?, feeraterestrict = ?
         WHERE gatewayrouting_id = ?`,
        [
          body.callerPrefixesAllow ?? 0, body.callerPrefixes || "",
          body.calleePrefixesAllow ?? 0, body.calleePrefixes || "",
          body.forwardingPrefixes || "",
          body.callerBlacklistPolicy ?? 0, body.calleeBlacklistPolicy ?? 0,
          body.rewriteRulesInCallee || "", body.rewriteRulesInCaller || "",
          body.denyCallerCallee || "",
          body.scheduledCapacity || "", body.scheduledPriority || "",
          body.scheduledCallinPrefixes || "", body.scheduledRewriteRulesIn || "",
          body.sipCodecs || "", body.h323Codecs || "",
          body.timeoutInvite ?? 30, body.timeoutRinging ?? 60,
          body.callerCityE164Check ?? 0,
          body.calleeCityE164Check ?? 0,
          body.stopSwitchAfterOlc ?? 0,
          body.clearingAccountUseCalloutE164 ?? 0,
          body.q931PresentationIndicator ?? 0,
          body.q931ScreeningIndicator ?? 0,
          body.dtmfReceiveMethod ?? 0,
          body.dtmfSendMethodH323 ?? 0,
          body.dtmfSendMethodSip ?? 0,
          body.dtmfReceivePayloadType ?? 0,
          body.dtmfSendPayloadTypeH323 ?? 0,
          body.dtmfSendPayloadTypeSip ?? 0,
          body.q931NumberingPlan ?? 0,
          body.q931NumberType ?? 0,
          body.sipResponseAddressMethod ?? 0,
          body.sipRequestAddressMethod ?? 0,
          body.bitsOfH323Config ?? 0,
          body.bitsOfSipConfig ?? 0,
          body.callerAllowLength ?? 0,
          body.calleeAllowLength ?? 0,
          body.leastCostRouting ?? 0,
          body.h323G729SendMode ?? 0,
          body.sipG729SendMode ?? 0,
          body.sipG729AnnexB ?? 0,
          body.sipG723AnnexA ?? 0,
          body.mediaCheckDirection ?? 0,
          body.enableCallTransfer ?? 0,
          body.maxCallDurationLower ?? 0,
          body.maxCallDurationUpper ?? 0,
          body.calleeE164Restrict ?? 0,
          body.enablePhoneDisplay ?? 0,
          body.switchUntilConnect ?? 0,
          body.maxCallRate ?? 0,
          body.maxCallRateUnit ?? 0,
          body.sipRemotePartyIdScreen ?? 0,
          body.sipE164DisplayType ?? 0,
          body.sipPrivacyType ?? 0,
          body.sipPPreferredIdentityType ?? 0,
          body.sipPAssertedIdentityType ?? 0,
          body.rewriteRulesInCallerUseE164Line ?? 0,
          body.bitsOfConfig ?? 0,
          body.traceEndTime ?? 0,
          body.externalNumberVerifyBits ?? 0,
          body.aasSampling ?? 0.0,
          body.denySameCityCodes || "",
          body.checkMobileArea || "",
          body.rewriteRulesInMobileArea || "",
          body.rewriteRulesPIdentity || "",
          body.axbBRewriteRules || "",
          body.externalNumberVerifyRewriteCaller || "",
          body.externalNumberVerifyRewriteCallee || "",
          body.rewriteRulesInCallerUseE164Group || "",
          body.callerLimitE164Groups || "",
          body.calleeLimitE164Groups || "",
          body.sipInviteCode || "",
          body.sipAuthenticationUser || "",
          body.sipExtraHeader || "",
          body.forwardSignalRewriteE164Group || "",
          body.aasWordCategory || "",
          body.axbAGroup || "",
          body.axbInterface || "",
          body.axbAccount || "",
          body.timeoutSetup ?? 0,
          body.timeoutCallProceeding ?? 0,
          body.timeoutCallProceedingOlc ?? 0,
          body.timeoutAlerting ?? 0,
          body.timeoutTrying ?? 0,
          body.timeoutSessionProgressSdp ?? 0,
          body.timeoutSessionProgress ?? 0,
          body.localIp || "",
          body.stopSwitchAfterUserBusy ?? 0, body.stopSwitchAfterSdp ?? 0,
          body.stopSwitchAfterRtpStart ?? 0, body.stopSwitchSipCodes || "",
          body.calculateQuality ?? 0, body.minProfitPercent ?? 0,
          body.maxSecondRates ?? 0, body.feeRateRestrict ?? 0,
          gwId,
        ]
      );
    } catch (settingErr) {
      // If no settings row exists yet, insert one
      await executeVos(
        `INSERT INTO e_gatewayroutingsetting (gatewayrouting_id, callincallerprefixesallow, callincallerprefixes,
          callincalleeprefixesallow, callincalleeprefixes, callinforwardprefixes,
          callerblacklistpolicy, calleeblacklistpolicy,
          rewriterulesincallee, rewriterulesincaller, denycallercallee,
          scheduledcapacity, scheduledpriority, scheduledcallinprefixes, scheduledrewriterulesin,
          sipcodecs, h323codecs, timeoutinvite, timeoutringing,
          callercitye164check,
          calleecitye164check,
          stopswitchafterolc,
          clearingaccountusecalloute164,
          q931presentationindicator,
          q931screeningindicator,
          dtmfreceivemethod,
          dtmfsendmethodh323,
          dtmfsendmethodsip,
          dtmfreceivepayloadtype,
          dtmfsendpayloadtypeh323,
          dtmfsendpayloadtypesip,
          q931numberingplan,
          q931numbertype,
          sipresponseaddressmethod,
          siprequestaddressmethod,
          bitsofh323config,
          bitsofsipconfig,
          callerallowlength,
          calleeallowlength,
          leastcostrouting,
          h323g729sendmode,
          sipg729sendmode,
          sipg729annexb,
          sipg723annexa,
          mediacheckdirection,
          enablecalltransfer,
          maxcalldurationlower,
          maxcalldurationupper,
          calleee164restrict,
          enablephonedisplay,
          switchuntilconnect,
          maxcallrate,
          maxcallrateunit,
          sipremotepartyidscreen,
          sipe164displaytype,
          sipprivacytype,
          sipppreferredidentitytype,
          sippassertedidentitytype,
          rewriterulesincallerusee164line,
          bitsofconfig,
          traceendtime,
          externalNumberVerifyBits,
          aassampling,
          denysamecitycodes,
          checkmobilearea,
          rewriterulesinmobilearea,
          rewriterulespidentity,
          axbbrewriterules,
          externalNumberVerfiyRewriteCaller,
          externalNumberVerfiyRewriteCallee,
          rewriterulesincallerusee164group,
          callerlimite164groups,
          calleelimite164groups,
          sipinvitecode,
          sipauthenticationuser,
          sipextraheader,
          forwardsignalrewritee164group,
          aaswordcategory,
          axbagroup,
          axbinterface,
          axbaccount,
          timeoutsetup,
          timeoutcallproceeding,
          timeoutcallproceedingolc,
          timeoutalerting,
          timeouttrying,
          timeoutsessionprogresssdp,
          timeoutsessionprogress,
          localip, stopswitchafteruserbusy, stopswitchaftersdp, stopswitchafterrtpstart, stopswitchsipcodes,
          calculatequality, minprofitpercent, maxsecondrates, feeraterestrict)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [gwId,
          body.callerPrefixesAllow ?? 0, body.callerPrefixes || "",
          body.calleePrefixesAllow ?? 0, body.calleePrefixes || "",
          body.forwardingPrefixes || "",
          body.callerBlacklistPolicy ?? 0, body.calleeBlacklistPolicy ?? 0,
          body.rewriteRulesInCallee || "", body.rewriteRulesInCaller || "", body.denyCallerCallee || "",
          body.scheduledCapacity || "", body.scheduledPriority || "", body.scheduledCallinPrefixes || "", body.scheduledRewriteRulesIn || "",
          body.sipCodecs || "", body.h323Codecs || "",
          body.timeoutInvite ?? 30, body.timeoutRinging ?? 60,
          body.localIp || "",
          body.stopSwitchAfterUserBusy ?? 0, body.stopSwitchAfterSdp ?? 0,
          body.stopSwitchAfterRtpStart ?? 0, body.stopSwitchSipCodes || "",
          body.calculateQuality ?? 0, body.minProfitPercent ?? 0,
          body.maxSecondRates ?? 0, body.feeRateRestrict ?? 0,
        ]
      );
    }

    return NextResponse.json({ success: true });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed to update routing gateway" }, { status: 500 });
  }
}

export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const { id } = await params;
    await executeVos("DELETE FROM e_gatewayrouting WHERE id = ?", [parseInt(id)]);
    return NextResponse.json({ success: true });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed to delete routing gateway" }, { status: 500 });
  }
}
