"use client";

import { useState, useEffect } from "react";
import { ClipboardList, RefreshCw } from "lucide-react";
import DataTable, { type Column } from "@/components/DataTable";

interface Report { id: number; date: string; createTime: number; loginName: string; types: number; memo: string; }

export default function ReportManagementPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const fetchReports = async () => {
    setLoading(true); setError("");
    try { const r=await fetch("/api/vos/report-management"); const d=await r.json(); if(d.error)setError(d.error); else setReports(d.reports||[]); } catch { setError("Failed"); }
    finally { setLoading(false); }
  };

  useEffect(()=>{fetchReports();},[]);

  const fmtTime = (t:number) => t ? new Date(t * 1000).toLocaleString("en-US", { year:"numeric", month:"short", day:"numeric", hour:"2-digit", minute:"2-digit" }) : "—";

  const columns: Column<Report>[] = [
    { key: "id", label: "#", render: (r) => <span className="text-surface-500 text-xs">{r.id}</span> },
    { key: "date", label: "Report Date", cellClassName: "text-surface-50 font-medium font-mono text-xs" },
    { key: "createTime", label: "Generated", render: (r) => <span className="text-xs text-surface-400">{fmtTime(r.createTime)}</span> },
    { key: "loginName", label: "Generated By", render: (r) => r.loginName || "—" },
    { key: "types", label: "Type", textAlign: "center" as const, render: (r) => <span className="px-2 py-0.5 rounded text-[11px] bg-surface-800 text-surface-400">Type {r.types}</span> },
    { key: "memo", label: "Memo", render: (r) => r.memo || "—", cellClassName: "text-surface-400" },
  ];

  return (<div className="p-6 space-y-6">
    <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-surface-50">Report Management</h1><p className="text-surface-400 text-sm mt-1">{reports.length} generated reports</p></div>
    <button onClick={fetchReports} className="flex items-center gap-2 px-4 py-2 rounded-lg bg-surface-800 text-surface-300 hover:bg-surface-700 text-sm"><RefreshCw className={`w-4 h-4 ${loading?"animate-spin":""}`}/>Refresh</button></div>

    {error&&<div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-400 text-sm">{error}</div>}

    <DataTable columns={columns} data={reports} searchKey="loginName" loading={loading} emptyMessage="No reports found" emptyIcon={<ClipboardList className="w-10 h-10 text-surface-600" />} pageSize={20} />
  </div>);
}
