import { NextRequest, NextResponse } from "next/server";
import { queryVos, executeVos } from "@/lib/vos-db";
import { verifySession } from "@/lib/auth";
import { nextMitId } from "@/lib/mit-ids";

export async function GET(request: NextRequest) {
  const user = await verifySession();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const { searchParams } = new URL(request.url);
    const search = searchParams.get("search") || "";

    let where = "";
    const params: (string | number)[] = [];

    if (search) {
      where = " WHERE r.name LIKE ? OR r.prefix LIKE ? OR r.remoteips LIKE ?";
      params.push(`%${search}%`, `%${search}%`, `%${search}%`);
    }

    const sql = `SELECT r.id, r.name, r.prefix, r.prefixstyle, r.password, r.customerpassword,
      r.locktype, r.calllevel, r.capacity, r.priority, r.iptype, r.encrypt, r.protocol,
      r.remoteips, r.rtpforwardtype, r.signalport, r.signalportlocal, r.gatewaygroups, r.memo,
      r.mbx_id, r.clearingcustomer_id,
      s.rewriterulesincallee, s.rewriterulesincaller, s.sipcodecs, s.h323codecs,
      s.timeoutinvite, s.timeoutringing, s.callerblacklistpolicy, s.calleeblacklistpolicy,
      s.callincallerprefixesallow, s.callincallerprefixes, s.callincalleeprefixesallow, s.callincalleeprefixes,
      s.callinforwardprefixes, s.denycallercallee,
      s.scheduledcapacity, s.scheduledpriority, s.scheduledcallinprefixes, s.scheduledrewriterulesin,
      s.callinmappinggateways,
      s.callercitye164check,
      s.calleecitye164check,
      s.stopswitchafterolc,
      s.clearingaccountusecalloute164,
      s.q931presentationindicator,
      s.q931screeningindicator,
      s.dtmfreceivemethod,
      s.dtmfsendmethodh323,
      s.dtmfsendmethodsip,
      s.dtmfreceivepayloadtype,
      s.dtmfsendpayloadtypeh323,
      s.dtmfsendpayloadtypesip,
      s.q931numberingplan,
      s.q931numbertype,
      s.sipresponseaddressmethod,
      s.siprequestaddressmethod,
      s.bitsofh323config,
      s.bitsofsipconfig,
      s.callerallowlength,
      s.calleeallowlength,
      s.leastcostrouting,
      s.h323g729sendmode,
      s.sipg729sendmode,
      s.sipg729annexb,
      s.sipg723annexa,
      s.mediacheckdirection,
      s.enablecalltransfer,
      s.maxcalldurationlower,
      s.maxcalldurationupper,
      s.calleee164restrict,
      s.enablephonedisplay,
      s.switchuntilconnect,
      s.maxcallrate,
      s.maxcallrateunit,
      s.sipremotepartyidscreen,
      s.sipe164displaytype,
      s.sipprivacytype,
      s.sipppreferredidentitytype,
      s.sippassertedidentitytype,
      s.rewriterulesincallerusee164line,
      s.bitsofconfig,
      s.traceendtime,
      s.externalNumberVerifyBits,
      s.aassampling,
      s.denysamecitycodes,
      s.checkmobilearea,
      s.rewriterulesinmobilearea,
      s.rewriterulespidentity,
      s.axbbrewriterules,
      s.externalNumberVerfiyRewriteCaller,
      s.externalNumberVerfiyRewriteCallee,
      s.rewriterulesincallerusee164group,
      s.callerlimite164groups,
      s.calleelimite164groups,
      s.sipinvitecode,
      s.sipauthenticationuser,
      s.sipextraheader,
      s.forwardsignalrewritee164group,
      s.aaswordcategory,
      s.axbagroup,
      s.axbinterface,
      s.axbaccount,
      s.timeoutsetup,
      s.timeoutcallproceeding,
      s.timeoutcallproceedingolc,
      s.timeoutalerting,
      s.timeouttrying,
      s.timeoutsessionprogresssdp,
      s.timeoutsessionprogress,
      s.localip, s.stopswitchafteruserbusy, s.stopswitchaftersdp, s.stopswitchafterrtpstart,
      s.stopswitchsipcodes, s.calculatequality, s.minprofitpercent, s.maxsecondrates, s.feeraterestrict,
      clr.name AS clearing_name, clr.account AS clearing_account, clr.money AS clearing_balance,
      clr.limitmoney AS clearing_limit
      FROM e_gatewayrouting r
      LEFT JOIN e_gatewayroutingsetting s ON r.id = s.gatewayrouting_id
      LEFT JOIN e_customer clr ON r.clearingcustomer_id = clr.id
      ${where}
      ORDER BY r.priority ASC, r.id ASC`;

    const rows = await queryVos<any>(sql, params);

    const gateways = (rows as any[]).map((r: any) => ({
      id: r.id,
      name: r.name,
      prefix: r.prefix,
      prefixStyle: r.prefixstyle,
      password: r.password || "",
      customerPassword: r.customerpassword || "",
      lockType: r.locktype,
      callLevel: r.calllevel,
      capacity: r.capacity,
      priority: r.priority,
      ipType: r.iptype,
      encrypt: r.encrypt,
      protocol: r.protocol,
      remoteIps: r.remoteips,
      rtpForwardType: r.rtpforwardtype,
      signalPort: r.signalport,
      signalPortLocal: r.signalportlocal,
      gatewayGroups: r.gatewaygroups,
      memo: r.memo,
      mbxId: r.mbx_id,
      clearingCustomerId: r.clearingcustomer_id,
      rewriteInCallee: r.rewriterulesincallee || null,
      rewriteInCaller: r.rewriterulesincaller || null,
      sipCodecs: r.sipcodecs || null,
      h323Codecs: r.h323codecs || null,
      timeoutInvite: r.timeoutinvite,
      timeoutRinging: r.timeoutringing,
      callerBlacklistPolicy: r.callerblacklistpolicy || 0,
      calleeBlacklistPolicy: r.calleeblacklistpolicy || 0,
      callerPrefixesAllow: r.callincallerprefixesallow || 0,
      callerPrefixes: r.callincallerprefixes || "",
      calleePrefixesAllow: r.callincalleeprefixesallow || 0,
      calleePrefixes: r.callincalleeprefixes || "",
      forwardingPrefixes: r.callinforwardprefixes || "",
      denyCallerCallee: r.denycallercallee || "",
      scheduledCapacity: r.scheduledcapacity || "",
      scheduledPriority: r.scheduledpriority || "",
      scheduledCallinPrefixes: r.scheduledcallinprefixes || "",
      scheduledRewriteRulesIn: r.scheduledrewriterulesin || "",
      mappingGatewayNames: r.callinmappinggateways || "",
      callerCityE164Check: r.callercitye164check ?? 0,
      calleeCityE164Check: r.calleecitye164check ?? 0,
      stopSwitchAfterOlc: r.stopswitchafterolc ?? 0,
      clearingAccountUseCalloutE164: r.clearingaccountusecalloute164 ?? 0,
      q931PresentationIndicator: r.q931presentationindicator ?? 0,
      q931ScreeningIndicator: r.q931screeningindicator ?? 0,
      dtmfReceiveMethod: r.dtmfreceivemethod ?? 0,
      dtmfSendMethodH323: r.dtmfsendmethodh323 ?? 0,
      dtmfSendMethodSip: r.dtmfsendmethodsip ?? 0,
      dtmfReceivePayloadType: r.dtmfreceivepayloadtype ?? 0,
      dtmfSendPayloadTypeH323: r.dtmfsendpayloadtypeh323 ?? 0,
      dtmfSendPayloadTypeSip: r.dtmfsendpayloadtypesip ?? 0,
      q931NumberingPlan: r.q931numberingplan ?? 0,
      q931NumberType: r.q931numbertype ?? 0,
      sipResponseAddressMethod: r.sipresponseaddressmethod ?? 0,
      sipRequestAddressMethod: r.siprequestaddressmethod ?? 0,
      bitsOfH323Config: r.bitsofh323config ?? 0,
      bitsOfSipConfig: r.bitsofsipconfig ?? 0,
      callerAllowLength: r.callerallowlength ?? 0,
      calleeAllowLength: r.calleeallowlength ?? 0,
      leastCostRouting: r.leastcostrouting ?? 0,
      h323G729SendMode: r.h323g729sendmode ?? 0,
      sipG729SendMode: r.sipg729sendmode ?? 0,
      sipG729AnnexB: r.sipg729annexb ?? 0,
      sipG723AnnexA: r.sipg723annexa ?? 0,
      mediaCheckDirection: r.mediacheckdirection ?? 0,
      enableCallTransfer: r.enablecalltransfer ?? 0,
      maxCallDurationLower: r.maxcalldurationlower ?? 0,
      maxCallDurationUpper: r.maxcalldurationupper ?? 0,
      calleeE164Restrict: r.calleee164restrict ?? 0,
      enablePhoneDisplay: r.enablephonedisplay ?? 0,
      switchUntilConnect: r.switchuntilconnect ?? 0,
      maxCallRate: r.maxcallrate ?? 0,
      maxCallRateUnit: r.maxcallrateunit ?? 0,
      sipRemotePartyIdScreen: r.sipremotepartyidscreen ?? 0,
      sipE164DisplayType: r.sipe164displaytype ?? 0,
      sipPrivacyType: r.sipprivacytype ?? 0,
      sipPPreferredIdentityType: r.sipppreferredidentitytype ?? 0,
      sipPAssertedIdentityType: r.sippassertedidentitytype ?? 0,
      rewriteRulesInCallerUseE164Line: r.rewriterulesincallerusee164line ?? 0,
      bitsOfConfig: r.bitsofconfig ?? 0,
      traceEndTime: r.traceendtime ?? 0,
      externalNumberVerifyBits: r.externalNumberVerifyBits ?? 0,
      aasSampling: Number(r.aassampling) || 0,
      denySameCityCodes: r.denysamecitycodes || "",
      checkMobileArea: r.checkmobilearea || "",
      rewriteRulesInMobileArea: r.rewriterulesinmobilearea || "",
      rewriteRulesPIdentity: r.rewriterulespidentity || "",
      axbBRewriteRules: r.axbbrewriterules || "",
      externalNumberVerifyRewriteCaller: r.externalNumberVerfiyRewriteCaller || "",
      externalNumberVerifyRewriteCallee: r.externalNumberVerfiyRewriteCallee || "",
      rewriteRulesInCallerUseE164Group: r.rewriterulesincallerusee164group || "",
      callerLimitE164Groups: r.callerlimite164groups || "",
      calleeLimitE164Groups: r.calleelimite164groups || "",
      sipInviteCode: r.sipinvitecode || "",
      sipAuthenticationUser: r.sipauthenticationuser || "",
      sipExtraHeader: r.sipextraheader || "",
      forwardSignalRewriteE164Group: r.forwardsignalrewritee164group || "",
      aasWordCategory: r.aaswordcategory || "",
      axbAGroup: r.axbagroup || "",
      axbInterface: r.axbinterface || "",
      axbAccount: r.axbaccount || "",
      timeoutSetup: r.timeoutsetup ?? 0,
      timeoutCallProceeding: r.timeoutcallproceeding ?? 0,
      timeoutCallProceedingOlc: r.timeoutcallproceedingolc ?? 0,
      timeoutAlerting: r.timeoutalerting ?? 0,
      timeoutTrying: r.timeouttrying ?? 0,
      timeoutSessionProgressSdp: r.timeoutsessionprogresssdp ?? 0,
      timeoutSessionProgress: r.timeoutsessionprogress ?? 0,
      localIp: r.localip || "",
      stopSwitchAfterUserBusy: r.stopswitchafteruserbusy ?? 0,
      stopSwitchAfterSdp: r.stopswitchaftersdp ?? 0,
      stopSwitchAfterRtpStart: r.stopswitchafterrtpstart ?? 0,
      stopSwitchSipCodes: r.stopswitchsipcodes || "",
      calculateQuality: r.calculatequality ?? 0,
      minProfitPercent: r.minprofitpercent ?? 0,
      maxSecondRates: r.maxsecondrates ?? 0,
      feeRateRestrict: r.feeraterestrict ?? 0,
      clearingName: r.clearing_name || "",
      clearingAccount: r.clearing_account || "",
      clearingBalance: Number(r.clearing_balance) || 0,
      clearingLimit: Number(r.clearing_limit) || 0,
    }));

    return NextResponse.json({ gateways });
  } catch (e: any) {
    console.error("[routing GET]", e?.message || e);
    return NextResponse.json({ error: e?.message || "Failed", gateways: [] }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  const user = await verifySession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const body = await request.json();
    // Gateway ids are MIT node ids — allocate a globally-unique id.
    const nextId = await nextMitId();

    await executeVos(
      `INSERT INTO e_gatewayrouting (id, name, prefix, prefixstyle, password, customerpassword, locktype, calllevel, capacity, priority, iptype, encrypt, protocol, remoteips, rtpforwardtype, signalport, signalportlocal, gatewaygroups, memo, mbx_id, clearingcustomer_id)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        nextId,
        body.name || "",
        body.prefix || "",
        body.prefixStyle ?? 0,
        body.password || "",
        body.customerPassword || "",
        body.lockType ?? 0,
        body.callLevel ?? 0,
        body.capacity ?? 30,
        body.priority ?? 1,
        body.ipType ?? 0,
        body.encrypt ?? 0,
        body.protocol ?? 0,
        body.remoteIps || "",
        body.rtpForwardType ?? 0,
        body.signalPort ?? 5060,
        body.signalPortLocal ?? 5060,
        body.gatewayGroups || "",
        body.memo || "",
        body.mbxId ?? 0,
        body.clearingCustomerId ?? 0,
      ]
    );

    // Create corresponding settings row with all provided fields
    try {
      await executeVos(
        `INSERT INTO e_gatewayroutingsetting (gatewayrouting_id, callincallerprefixesallow, callincallerprefixes,
          callincalleeprefixesallow, callincalleeprefixes, callinforwardprefixes,
          callerblacklistpolicy, calleeblacklistpolicy,
          rewriterulesincallee, rewriterulesincaller, denycallercallee,
          scheduledcapacity, scheduledpriority, scheduledcallinprefixes, scheduledrewriterulesin,
          sipcodecs, h323codecs, timeoutinvite, timeoutringing,
          callercitye164check,
          calleecitye164check,
          stopswitchafterolc,
          clearingaccountusecalloute164,
          q931presentationindicator,
          q931screeningindicator,
          dtmfreceivemethod,
          dtmfsendmethodh323,
          dtmfsendmethodsip,
          dtmfreceivepayloadtype,
          dtmfsendpayloadtypeh323,
          dtmfsendpayloadtypesip,
          q931numberingplan,
          q931numbertype,
          sipresponseaddressmethod,
          siprequestaddressmethod,
          bitsofh323config,
          bitsofsipconfig,
          callerallowlength,
          calleeallowlength,
          leastcostrouting,
          h323g729sendmode,
          sipg729sendmode,
          sipg729annexb,
          sipg723annexa,
          mediacheckdirection,
          enablecalltransfer,
          maxcalldurationlower,
          maxcalldurationupper,
          calleee164restrict,
          enablephonedisplay,
          switchuntilconnect,
          maxcallrate,
          maxcallrateunit,
          sipremotepartyidscreen,
          sipe164displaytype,
          sipprivacytype,
          sipppreferredidentitytype,
          sippassertedidentitytype,
          rewriterulesincallerusee164line,
          bitsofconfig,
          traceendtime,
          externalNumberVerifyBits,
          aassampling,
          denysamecitycodes,
          checkmobilearea,
          rewriterulesinmobilearea,
          rewriterulespidentity,
          axbbrewriterules,
          externalNumberVerfiyRewriteCaller,
          externalNumberVerfiyRewriteCallee,
          rewriterulesincallerusee164group,
          callerlimite164groups,
          calleelimite164groups,
          sipinvitecode,
          sipauthenticationuser,
          sipextraheader,
          forwardsignalrewritee164group,
          aaswordcategory,
          axbagroup,
          axbinterface,
          axbaccount,
          timeoutsetup,
          timeoutcallproceeding,
          timeoutcallproceedingolc,
          timeoutalerting,
          timeouttrying,
          timeoutsessionprogresssdp,
          timeoutsessionprogress,
          localip, stopswitchafteruserbusy, stopswitchaftersdp, stopswitchafterrtpstart, stopswitchsipcodes,
          calculatequality, minprofitpercent, maxsecondrates, feeraterestrict)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [nextId,
          body.callerPrefixesAllow ?? 1, body.callerPrefixes || "",
          body.calleePrefixesAllow ?? 1, body.calleePrefixes || "",
          body.forwardingPrefixes || "",
          body.callerBlacklistPolicy ?? 0, body.calleeBlacklistPolicy ?? 0,
          body.rewriteRulesInCaller || "", body.rewriteRulesInCallee || "",
          body.denyCallerCallee || "",
          body.scheduledCapacity || "", body.scheduledPriority || "",
          body.scheduledCallinPrefixes || "", body.scheduledRewriteRulesIn || "",
          body.sipCodecs || "", body.h323Codecs || "",
          body.timeoutInvite ?? 30, body.timeoutRinging ?? 60,
          body.callerCityE164Check ?? 0,
          body.calleeCityE164Check ?? 0,
          body.stopSwitchAfterOlc ?? 0,
          body.clearingAccountUseCalloutE164 ?? 0,
          body.q931PresentationIndicator ?? 0,
          body.q931ScreeningIndicator ?? 0,
          body.dtmfReceiveMethod ?? 0,
          body.dtmfSendMethodH323 ?? 0,
          body.dtmfSendMethodSip ?? 0,
          body.dtmfReceivePayloadType ?? 0,
          body.dtmfSendPayloadTypeH323 ?? 0,
          body.dtmfSendPayloadTypeSip ?? 0,
          body.q931NumberingPlan ?? 0,
          body.q931NumberType ?? 0,
          body.sipResponseAddressMethod ?? 0,
          body.sipRequestAddressMethod ?? 0,
          body.bitsOfH323Config ?? 0,
          body.bitsOfSipConfig ?? 0,
          body.callerAllowLength ?? 0,
          body.calleeAllowLength ?? 0,
          body.leastCostRouting ?? 0,
          body.h323G729SendMode ?? 0,
          body.sipG729SendMode ?? 0,
          body.sipG729AnnexB ?? 0,
          body.sipG723AnnexA ?? 0,
          body.mediaCheckDirection ?? 0,
          body.enableCallTransfer ?? 0,
          body.maxCallDurationLower ?? 0,
          body.maxCallDurationUpper ?? 0,
          body.calleeE164Restrict ?? 0,
          body.enablePhoneDisplay ?? 0,
          body.switchUntilConnect ?? 0,
          body.maxCallRate ?? 0,
          body.maxCallRateUnit ?? 0,
          body.sipRemotePartyIdScreen ?? 0,
          body.sipE164DisplayType ?? 0,
          body.sipPrivacyType ?? 0,
          body.sipPPreferredIdentityType ?? 0,
          body.sipPAssertedIdentityType ?? 0,
          body.rewriteRulesInCallerUseE164Line ?? 0,
          body.bitsOfConfig ?? 0,
          body.traceEndTime ?? 0,
          body.externalNumberVerifyBits ?? 0,
          body.aasSampling ?? 0.0,
          body.denySameCityCodes || "",
          body.checkMobileArea || "",
          body.rewriteRulesInMobileArea || "",
          body.rewriteRulesPIdentity || "",
          body.axbBRewriteRules || "",
          body.externalNumberVerifyRewriteCaller || "",
          body.externalNumberVerifyRewriteCallee || "",
          body.rewriteRulesInCallerUseE164Group || "",
          body.callerLimitE164Groups || "",
          body.calleeLimitE164Groups || "",
          body.sipInviteCode || "",
          body.sipAuthenticationUser || "",
          body.sipExtraHeader || "",
          body.forwardSignalRewriteE164Group || "",
          body.aasWordCategory || "",
          body.axbAGroup || "",
          body.axbInterface || "",
          body.axbAccount || "",
          body.timeoutSetup ?? 0,
          body.timeoutCallProceeding ?? 0,
          body.timeoutCallProceedingOlc ?? 0,
          body.timeoutAlerting ?? 0,
          body.timeoutTrying ?? 0,
          body.timeoutSessionProgressSdp ?? 0,
          body.timeoutSessionProgress ?? 0,
          body.localIp || "",
          body.stopSwitchAfterUserBusy ?? 0, body.stopSwitchAfterSdp ?? 0,
          body.stopSwitchAfterRtpStart ?? 0, body.stopSwitchSipCodes || "",
          body.calculateQuality ?? 0, body.minProfitPercent ?? 0,
          body.maxSecondRates ?? 0, body.feeRateRestrict ?? 0,
        ]
      );
    } catch (settingsErr) {
      // Clean up the gateway if settings can't be created
      try { await executeVos("DELETE FROM e_gatewayrouting WHERE id = ?", [nextId]); } catch {}
      return NextResponse.json({ error: "Gateway created but settings initialization failed — rolled back" }, { status: 500 });
    }

    return NextResponse.json({ success: true, id: nextId });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Failed to create routing gateway" }, { status: 500 });
  }
}
